title: Standardizing Service Mesh Value Measurement
email: community@layer5.io #this is also the email contact forms will go
description: "Service Mesh Performance Specification (SMPS): Measure your service mesh performance using the SMPS.
     provides a universal performance index to gauge your mesh’s efficiency against deployments in other organizations’ environments."
baseurl: "" # the subpath of your site, e.g. /blog

author: Layer5 Authors
twitter_username: layer5
github_username:  l5io

logo:
  path: assets/img/smps-white.svg
  height: 80px #height in px, defaults to 52px

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jemoji
  - jekyll-coffeescript

analytics:
  google: UA-152604689-2

collections:
  portfolio:

markdown: kramdown
