# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.
# This file is *NOT* reloaded automatically when you use 'bundle exec jekyll serve'.
# If you change this file, please restart the server process.

# Site settings
# are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

theme: jekyll-agency

title: Service Mesh Performance Specification
email: community@layer5.io
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog


title      : Service Mesh Performance Specification
email      : community@layer5.io #this is also the email contact forms will go to
description: "Site description"
author     : Layer5 Authors

twitter_username: layer5
github_username:  l5io

logo:     #optional, defaults to site title
  path: assets/img/smps-new-logo.png
  height: 100 #height in px, defaults to 52px
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jemoji
  - jekyll-coffeescript


analytics:
  google: #Google Analytics tracking code here

collections:
  portfolio:

markdown: kramdown
